// <auto-generated />
namespace HCCADBWebAppPrototype1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class updatedmodelswithdatatypevalidation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatedmodelswithdatatypevalidation));
        
        string IMigrationMetadata.Id
        {
            get { return "201405111234395_updated models with datatype validation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
