// <auto-generated />
namespace HCCADBWebAppPrototype1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class fixedissuewithareaofhealthjointable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fixedissuewithareaofhealthjointable));
        
        string IMigrationMetadata.Id
        {
            get { return "201404301040372_fixed issue with areaofhealth join table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
